# Generated by Django 2.2.7 on 2019-11-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='问卷名称')),
                ('description', models.TextField(blank=True, verbose_name='问卷说明')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='问题名称')),
                ('type', models.IntegerField(choices=[(0, '单选'), (1, '多选'), (2, '简答')], default=0, verbose_name='问题类型')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Table', verbose_name='问卷')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='选项内容')),
                ('poll', models.IntegerField(verbose_name='选择人数')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Question', verbose_name='问题')),
            ],
        ),
    ]
