# Generated by Django 2.2.7 on 2019-12-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_text', models.TextField(verbose_name='建议内容')),
            ],
            options={
                'verbose_name': '简答内容',
                'verbose_name_plural': '简答内容',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='选项内容')),
                ('poll', models.IntegerField(default=0, verbose_name='选择人数')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='问题名称')),
                ('type', models.IntegerField(choices=[(0, '单选'), (1, '多选'), (2, '简答')], default=0, verbose_name='问题类型')),
                ('status', models.IntegerField(choices=[(0, '发布'), (1, '暂不发布')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='问卷标题')),
                ('description', models.TextField(blank=True, verbose_name='问卷说明')),
                ('time', models.DateTimeField(verbose_name='创建时间')),
                ('status', models.IntegerField(choices=[(0, '发布'), (1, '暂不发布')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '问卷',
                'verbose_name_plural': '问卷',
            },
        ),
    ]
