# Generated by Django 2.2.7 on 2019-11-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20191130_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100, verbose_name='问题名称'),
        ),
    ]
