# Generated by Django 2.2.7 on 2019-12-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20191130_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': '问卷', 'verbose_name_plural': '问卷'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.IntegerField(default=0, verbose_name='选择人数'),
        ),
        migrations.AlterField(
            model_name='table',
            name='title',
            field=models.TextField(verbose_name='问卷标题'),
        ),
    ]
