# Generated by Django 2.2.7 on 2019-12-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20191201_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='title',
            field=models.CharField(max_length=50, verbose_name='选项内容'),
        ),
    ]
