# Generated by Django 2.2.7 on 2019-12-01 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20191201_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(0, '发布'), (1, '暂不发布')], default=0, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.IntegerField(choices=[(0, '发布'), (1, '暂不发布')], default=0, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='table',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
    ]
