# Generated by Django 2.2.7 on 2019-12-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20191201_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
    ]
