# Generated by Django 2.2.7 on 2019-12-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20191201_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(verbose_name='问题名称'),
        ),
    ]
