# Generated by Django 2.2.7 on 2019-12-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20191201_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_text', models.TextField(verbose_name='建议内容')),
                ('question_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Question', verbose_name='问题')),
            ],
            options={
                'verbose_name': '简答内容',
                'verbose_name_plural': '简答内容',
            },
        ),
    ]
