# Generated by Django 2.2.7 on 2019-12-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': '文件上传', 'verbose_name_plural': '文件上传'},
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='temp', max_length=50, verbose_name='文件名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.FileField(upload_to='files', verbose_name='上传文件'),
        ),
    ]
